name: TERRAFORM CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: terraform-ci
  cancel-in-progress: true

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          for dir in $(find . -type f -name "provider.tf" | xargs -n1 dirname | sort -u)
          do
            if [ -f "$dir/terraform.tf" ]; then
              (cd "$dir" && terraform init -backend=false)
            fi
          done  

      - name: Terraform Validate
        run: |
          for dir in $(find . -type f -name "provider.tf"  | xargs -n1 dirname | sort -u)
          do
            if [ -f "$dir/terraform.tf" ]; then
              (cd "$dir" && terraform validate)
            fi
          done